- CHANGELOG.md
- docs/components/query.md
> Add warning to query docs re: Dask RuntimeError

- CHANGELOG.md
- docs/components/query.md
- vasttools/query.py
> Allow query epochs to be specified as list or string

- CHANGELOG.md
- tests/test_pipeline.py
- tests/test_query.py
- tests/test_source.py
- vasttools/pipeline.py
- vasttools/query.py
- vasttools/source.py
- vasttools/survey.py
- vasttools/tools.py
* Migrated all uses to `pd.concat`.
Fixes #335.
> Fixed pandas append deprecation

- .github/workflows/lint.yml
- CHANGELOG.md
- docs/contributing/github.md
- docs/contributing/tests.md
- poetry.lock
- pyproject.toml
- tests/test_init.py
- tests/test_moc.py
- tests/test_pipeline.py
- tests/test_query.py
- tests/test_source.py
- tests/test_survey.py
- tests/test_tools.py
- tests/test_utils.py
- vasttools/bin/find_sources.py
- vasttools/moc.py
- vasttools/pipeline.py
- vasttools/query.py
- vasttools/source.py
- vasttools/survey.py
- vasttools/tools.py
- vasttools/utils.py
> Added pylint workflow for pull requests

- CHANGELOG.md
- vasttools/source.py
> Correctly implement legend on lightcurve

- CHANGELOG.md
- docs/contributing/newepoch.md
- vasttools/__init__.py
- vasttools/query.py
> Fix find_fields not returning RACS-mid fields

- CHANGELOG.md
- tests/test_query.py
- vasttools/query.py
- Also added test for find_sources with `search_around=True`.
- Fixes #364.
> Fix query search_around_coordinates option

- CHANGELOG.md
- vasttools/pipeline.py
Fix #381.
Fix #382.
Added logging to PipeRun class.
> Fix eta-V bokeh plotting and add logging to PipeRun class.

- CHANGELOG.md
- vasttools/query.py
> Fix read_selavy arguments in Query._get_cutout

- CHANGELOG.md
- vasttools/query.py
> Change self.planets to be an empty list if no input is provided

- CHANGELOG.md
- docs/components/query.md
- vasttools/query.py
> Fix query docs and logging

- CHANGELOG.md
- tests/test_query.py
- vasttools/query.py
> Fix stokes I hardcoding

- CHANGELOG.md
- vasttools/query.py
- vasttools/source.py
> Added corrected_data argument to Source class

- CHANGELOG.md
- vasttools/utils.py
> Correctly handle empty groups in match_planet_to_field

- .github/workflows/lint.yml
- .github/workflows/pytest.yml
- CHANGELOG.md
> Updated ubuntu version for lint and pytest actions

- CHANGELOG.md
- tests/test_query.py
- vasttools/bin/find_sources.py
- vasttools/pipeline.py
- vasttools/query.py
> Add dask scheduler switch

- CHANGELOG.md
- vasttools/source.py
> Correctly handle show_all_png_cutouts(save=True) file naming

- CHANGELOG.md
- docs/components/query.md
- vasttools/query.py
> Expand default value of max_sep in Query to 1.5

- .github/workflows/pytest.yml
> Updated setup-poetry to v8

- .github/workflows/pytest.yml
Reverts askap-vast/vast-tools#447
> Revert "Updated setup-poetry to v8"

- CHANGELOG.md
- vasttools/moc.py
> Updated VASTMOCS to correctly handle fields with/without 'A' suffix

- CHANGELOG.md
- vasttools/utils.py
> Update read_selavy to force all flux & flux err values to be positive

- CHANGELOG.md
- vasttools/query.py
> Remove duplicates in field matching

- CHANGELOG.md
- tests/test_survey.py
- vasttools/survey.py
> Fix missing RMS measurements for non-detections

- CHANGELOG.md
- vasttools/source.py
- vasttools/survey.py
> Ensure that full image data does not persist when creating FITS cutouts from compressed HDUs

- CHANGELOG.md
- tests/test_source.py
- vasttools/source.py
> Exit nicely when invalid survey is requested for SkyView contour plot

- vasttools/query.py
> Fix _grouped_fetch_cutouts dropping all cutouts.

- CHANGELOG.md
- vasttools/utils.py
> Update open_fits to check HDU list contents rather than the file extension.

- CHANGELOG.md
- vasttools/source.py
> Disable autoscaling for show_png_cutout

- CHANGELOG.md
- vasttools/utils.py
Hotfix for bug that was not actually fixed by #526.
> open_fits: check len(hdul) is 1, not 0

- CHANGELOG.md
- vasttools/source.py
> Convert all Source names to strings

- .github/workflows/pytest.yml
- CHANGELOG.md
> Update pytest actions
